### ISSUE TITLE
Transferencia de repositorio

### ISSUE THREAD

**Issue by ghost** [vcastrejont/rscss-es#4]
Puedo transferirte este repositorio, yo ya no tengo pensado mantenerlo. Solo necesitaría que eliminaras o renombraras el fork actual que tienes, para que me deje hacerlo.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/2559808/42359388-cd68e198-809e-11e8-8a9b-8ff54e93fd1a.png">

**Comment by vcastrejont** [comment]
@jameskolce Sure go ahead, I have deleted the fork

**Comment by ghost** [comment]
Done, you should have received some kind of notification
